/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Command from './Command';
import UserAuth from './UserAuth';





/**
* The Execute model module.
* @module model/Execute
* @version 2
*/
export default class Execute {
    /**
    * Constructs a new <code>Execute</code>.
    * @alias module:model/Execute
    * @class
    * @param command {module:model/Command} 
    */

    constructor(command) {
        

        
        

        this['command'] = command;

        
    }

    /**
    * Constructs a <code>Execute</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Execute} obj Optional instance to populate.
    * @return {module:model/Execute} The populated <code>Execute</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Execute();

            
            
            

            if (data.hasOwnProperty('command')) {
                obj['command'] = Command.constructFromObject(data['command']);
            }
            if (data.hasOwnProperty('auth')) {
                obj['auth'] = UserAuth.constructFromObject(data['auth']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Command} command
    */
    command = undefined;
    /**
    * @member {module:model/UserAuth} auth
    */
    auth = undefined;








}


