/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Script model module.
* @module model/Script
* @version 2
*/
export default class Script {
    /**
    * Constructs a new <code>Script</code>.
    * @alias module:model/Script
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Script</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Script} obj Optional instance to populate.
    * @return {module:model/Script} The populated <code>Script</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Script();

            
            
            

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} content
    */
    content = undefined;
    /**
    * @member {String} name
    */
    name = undefined;








}


