/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import Execute from '../model/Execute';
import Response from '../model/Response';

/**
* Commandtax service.
* @module api/CommandtaxApi
* @version 2
*/
export default class CommandtaxApi {

    /**
    * Constructs a new CommandtaxApi. 
    * @alias module:api/CommandtaxApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the command operation.
     * @callback module:api/CommandtaxApi~commandCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Execute a Command
     * Execute a command
     * @param {String} driver The driver to use for the request. ie. github
     * @param {Object} opts Optional parameters
     * @param {module:model/Execute} opts.execute The data needed to execute this command
     * @param {module:api/CommandtaxApi~commandCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Response}
     */
    command(driver, opts, callback) {
      opts = opts || {};
      let postBody = opts['execute'];

      // verify the required parameter 'driver' is set
      if (driver === undefined || driver === null) {
        throw new Error("Missing the required parameter 'driver' when calling command");
      }


      let pathParams = {
        'driver': driver
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/drivers/{driver}/commandtax/command', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
