/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UserAuth from './UserAuth';





/**
* The AuthResponse model module.
* @module model/AuthResponse
* @version 2
*/
export default class AuthResponse {
    /**
    * Constructs a new <code>AuthResponse</code>.
    * @alias module:model/AuthResponse
    * @class
    * @param status {Number} 
    * @param message {String} 
    */

    constructor(status, message) {
        

        
        

        this['status'] = status;this['message'] = message;

        
    }

    /**
    * Constructs a <code>AuthResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthResponse} obj Optional instance to populate.
    * @return {module:model/AuthResponse} The populated <code>AuthResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthResponse();

            
            
            

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
            if (data.hasOwnProperty('auth')) {
                obj['auth'] = UserAuth.constructFromObject(data['auth']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {String} access_token
    */
    access_token = undefined;
    /**
    * @member {String} refresh_token
    */
    refresh_token = undefined;
    /**
    * @member {module:model/UserAuth} auth
    */
    auth = undefined;








}


