/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Script from './Script';





/**
* The ScriptRename model module.
* @module model/ScriptRename
* @version 2
*/
export default class ScriptRename {
    /**
    * Constructs a new <code>ScriptRename</code>.
    * @alias module:model/ScriptRename
    * @class
    * @param original {module:model/Script} 
    * @param _new {module:model/Script} 
    */

    constructor(original, _new) {
        

        
        

        this['original'] = original;this['new'] = _new;

        
    }

    /**
    * Constructs a <code>ScriptRename</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ScriptRename} obj Optional instance to populate.
    * @return {module:model/ScriptRename} The populated <code>ScriptRename</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScriptRename();

            
            
            

            if (data.hasOwnProperty('original')) {
                obj['original'] = Script.constructFromObject(data['original']);
            }
            if (data.hasOwnProperty('new')) {
                obj['new'] = Script.constructFromObject(data['new']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Script} original
    */
    original = undefined;
    /**
    * @member {module:model/Script} new
    */
    new = undefined;








}


