/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import User from './User';





/**
* The UserDelete model module.
* @module model/UserDelete
* @version 2
*/
export default class UserDelete {
    /**
    * Constructs a new <code>UserDelete</code>.
    * @alias module:model/UserDelete
    * @class
    * @param script {module:model/User} 
    */

    constructor(script) {
        

        
        

        this['script'] = script;

        
    }

    /**
    * Constructs a <code>UserDelete</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserDelete} obj Optional instance to populate.
    * @return {module:model/UserDelete} The populated <code>UserDelete</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDelete();

            
            
            

            if (data.hasOwnProperty('script')) {
                obj['script'] = User.constructFromObject(data['script']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/User} script
    */
    script = undefined;








}


