/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apitax);
  }
}(this, function(expect, Apitax) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apitax.UserAuth();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserAuth', function() {
    it('should create an instance of UserAuth', function() {
      // uncomment below and update the code to test UserAuth
      //var instane = new Apitax.UserAuth();
      //expect(instance).to.be.a(Apitax.UserAuth);
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new Apitax.UserAuth();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new Apitax.UserAuth();
      //expect(instance).to.be();
    });

    it('should have the property apiToken (base name: "api_token")', function() {
      // uncomment below and update the code to test the property apiToken
      //var instane = new Apitax.UserAuth();
      //expect(instance).to.be();
    });

    it('should have the property extra (base name: "extra")', function() {
      // uncomment below and update the code to test the property extra
      //var instane = new Apitax.UserAuth();
      //expect(instance).to.be();
    });

  });

}));
