/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apitax);
  }
}(this, function(expect, Apitax) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apitax.DriversApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DriversApi', function() {
    describe('getDriverBlacklist', function() {
      it('should call getDriverBlacklist successfully', function(done) {
        //uncomment below and update the code to test getDriverBlacklist
        //instance.getDriverBlacklist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDriverConfig', function() {
      it('should call getDriverConfig successfully', function(done) {
        //uncomment below and update the code to test getDriverConfig
        //instance.getDriverConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDriverList', function() {
      it('should call getDriverList successfully', function(done) {
        //uncomment below and update the code to test getDriverList
        //instance.getDriverList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDriverStatus', function() {
      it('should call getDriverStatus successfully', function(done) {
        //uncomment below and update the code to test getDriverStatus
        //instance.getDriverStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDriverWhitelist', function() {
      it('should call getDriverWhitelist successfully', function(done) {
        //uncomment below and update the code to test getDriverWhitelist
        //instance.getDriverWhitelist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
