/**
 * Apitax
 * The API for the frontend of Apitax
 *
 * OpenAPI spec version: 2
 * Contact: shawn.clake@nopatience.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApitaxJsClient);
  }
}(this, function(expect, ApitaxJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApitaxJsClient.ScriptaxApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScriptaxApi', function() {
    describe('createDriverScript', function() {
      it('should call createDriverScript successfully', function(done) {
        //uncomment below and update the code to test createDriverScript
        //instance.createDriverScript(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDriverScript', function() {
      it('should call deleteDriverScript successfully', function(done) {
        //uncomment below and update the code to test deleteDriverScript
        //instance.deleteDriverScript(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDriverScript', function() {
      it('should call getDriverScript successfully', function(done) {
        //uncomment below and update the code to test getDriverScript
        //instance.getDriverScript(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDriverScriptCatalog', function() {
      it('should call getDriverScriptCatalog successfully', function(done) {
        //uncomment below and update the code to test getDriverScriptCatalog
        //instance.getDriverScriptCatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('renameDriverScript', function() {
      it('should call renameDriverScript successfully', function(done) {
        //uncomment below and update the code to test renameDriverScript
        //instance.renameDriverScript(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('saveDriverScript', function() {
      it('should call saveDriverScript successfully', function(done) {
        //uncomment below and update the code to test saveDriverScript
        //instance.saveDriverScript(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
